services:
#  cache:
#    image: redis:latest
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data
#    command: redis-server --save 180 1 --loglevel warning
#    env_file:
#      - .env

  buildmate:
    build:
      context: buildmate
      dockerfile: Dockerfile
    volumes:
      - ./buildmate/app:/buildmate/app
      - ./buildmate/tests:/buildmate/tests
    command: [ "python", "app/main.py" ]
    depends_on:
      - search
    env_file:
      - .env
      - keys.env

  search:
    build:
      context: search
      dockerfile: Dockerfile
    volumes:
      - ./search/app:/search/app
    command: [ "python", "app/main.py" ]
    env_file:
      - keys.env
      - .env
    ports:
      - "5000:5000"

  search-test:
    build:
      context: search_test
      dockerfile: Dockerfile
    depends_on:
      - search
    command: ["python", "app/main.py"]
    environment:
      SEARCH_URL: "http://search:5000/search"