services:
#  cache:
#    image: redis:latest
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data
#    command: redis-server --save 180 1 --loglevel warning
#    env_file:
#      - .env

  basic:
    build:
      context: basic
      dockerfile: Dockerfile
    volumes:
      - ./basic/app:/basic/app
      - ./basic/tests:/basic/tests
    command: [ "python", "app/basic.py" ]
    env_file:
      - .env
